@token = ACCESS_TOKEN_HERE

### 반려견 등록
POST http://localhost:8080/api/dogs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "초코",
  "breed": "말티즈",
  "birthDate": "2021-03-15",
  "weightKg": 3.2,
  "gender": "MALE",
  "isNeutered": true,
  "profileImage": null
}

###

### 내 반려견 전체 조회
GET http://localhost:8080/api/dogs
Authorization: Bearer {{token}}

###

### 반려견 단건 조회
GET http://localhost:8080/api/dogs/1
Authorization: Bearer {{token}}

###

### 반려견 수정
PATCH http://localhost:8080/api/dogs/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "초코",
  "breed": "말티즈",
  "birthDate": "2021-03-15",
  "weightKg": 3.5,
  "gender": "MALE",
  "isNeutered": true,
  "profileImage": null
}

###

### 반려견 삭제
DELETE http://localhost:8080/api/dogs/1
Authorization: Bearer {{token}}

###
